global using Xunit;
global using System.Net;
global using System.Text.Json;
global using FluentAssertions;
global using PodcastIndex.Net.Contracts.Enums;
global using System;
global using System.Threading;
global using System.Threading.Tasks;
global using NSubstitute;