namespace PodcastIndex.Net.Contracts;

/// <summary>
///     Helpers to make it easier to deal with either the api or providing static data like a dictionary with categories
///     without the need to call the api.
/// </summary>
public static class ContractHelpers
{
    /// <summary>
    ///     Rss language codes according to https://www.rssboard.org/rss-language-codes
    /// </summary>
    public static IReadOnlyDictionary<string, string> RssLanguagesCodes { get; private set; } =
        new Dictionary<string, string>
        {
            { "af", "Afrikaans" },
            { "sq", "Albanian" },
            { "eu", "Basque" },
            { "be", "Belarusian" },
            { "bg", "Bulgarian" },
            { "ca", "Catalan" },
            { "zh-cn", "Chinese (Simplified)" },
            { "zh-tw", "Chinese (Traditional)" },
            { "hr", "Croatian" },
            { "cs", "Czech" },
            { "da", "Danish" },
            { "nl", "Dutch" },
            { "nl-be", "Dutch (Belgium)" },
            { "nl-nl", "Dutch (Netherlands)" },
            { "en", "English" },
            { "en-au", "English (Australia)" },
            { "en-bz", "English (Belize)" },
            { "en-ca", "English (Canada)" },
            { "en-ie", "English (Ireland)" },
            { "en-jm", "English (Jamaica)" },
            { "en-nz", "English (New Zealand)" },
            { "en-ph", "English (Phillipines)" },
            { "en-za", "English (South Africa)" },
            { "en-tt", "English (Trinidad)" },
            { "en-gb", "English (United Kingdom)" },
            { "en-us", "English (United States)" },
            { "en-zw", "English (Zimbabwe)" },
            { "et", "Estonian" },
            { "fo", "Faeroese" },
            { "fi", "Finnish" },
            { "fr", "French" },
            { "fr-be", "French (Belgium)" },
            { "fr-ca", "French (Canada)" },
            { "fr-fr", "French (France)" },
            { "fr-lu", "French (Luxembourg)" },
            { "fr-mc", "French (Monaco)" },
            { "fr-ch", "French (Switzerland)" },
            { "gl", "Galician" },
            { "gd", "Gaelic" },
            { "de", "German" },
            { "de-at", "German (Austria)" },
            { "de-de", "German (Germany)" },
            { "de-li", "German (Liechtenstein)" },
            { "de-lu", "German (Luxembourg)" },
            { "de-ch", "German (Switzerland)" },
            { "el", "Greek" },
            { "haw", "Hawaiian" },
            { "hu", "Hungarian" },
            { "is", "Icelandic" },
            { "in", "Indonesian" },
            { "ga", "Irish" },
            { "it", "Italian" },
            { "it-it", "Italian (Italy)" },
            { "it-ch", "Italian (Switzerland)" },
            { "ja", "Japanese" },
            { "ko", "Korean" },
            { "mk", "Macedonian" },
            { "no", "Norwegian" },
            { "pl", "Polish" },
            { "pt", "Portuguese" },
            { "pt-br", "Portuguese (Brazil)" },
            { "pt-pt", "Portuguese (Portugal)" },
            { "ro", "Romanian" },
            { "ro-mo", "Romanian (Moldova)" },
            { "ro-ro", "Romanian (Romania)" },
            { "ru", "Russian" },
            { "ru-mo", "Russian (Moldova)" },
            { "ru-ru", "Russian (Russia)" },
            { "sr", "Serbian" },
            { "sk", "Slovak" },
            { "sl", "Slovenian" },
            { "es", "Spanish" },
            { "es-ar", "Spanish (Argentina)" },
            { "es-bo", "Spanish (Bolivia)" },
            { "es-cl", "Spanish (Chile)" },
            { "es-co", "Spanish (Colombia)" },
            { "es-cr", "Spanish (Costa Rica)" },
            { "es-do", "Spanish (Dominican Republic)" },
            { "es-ec", "Spanish (Ecuador)" },
            { "es-sv", "Spanish (El Salvador)" },
            { "es-gt", "Spanish (Guatemala)" },
            { "es-hn", "Spanish (Honduras)" },
            { "es-mx", "Spanish (Mexico)" },
            { "es-ni", "Spanish (Nicaragua)" },
            { "es-pa", "Spanish (Panama)" },
            { "es-py", "Spanish (Paraguay)" },
            { "es-pe", "Spanish (Peru)" },
            { "es-pr", "Spanish (Puerto Rico)" },
            { "es-es", "Spanish (Spain)" },
            { "es-uy", "Spanish (Uruguay)" },
            { "es-ve", "Spanish (Venezuela)" },
            { "sv", "Swedish" },
            { "sv-fi", "Swedish (Finland)" },
            { "sv-se", "Swedish (Sweden)" },
            { "tr", "Turkish" },
            { "uk", "Ukranian" }
        };

    /// <summary>
    ///     A static dictionary that contains all categories without the need to call
    ///     https://api.podcastindex.org/api/1.0/categories/list
    /// </summary>
    public static IReadOnlyDictionary<int, string> Categories { get; private set; } =
        new Dictionary<int, string>
        {
            { 1, "Arts" },
            { 2, "Books" },
            { 3, "Design" },
            { 4, "Fashion" },
            { 5, "Beauty" },
            { 6, "Food" },
            { 7, "Performing" },
            { 8, "Visual" },
            { 9, "Business" },
            { 10, "Careers" },
            { 11, "Entrepreneurship" },
            { 12, "Investing" },
            { 13, "Management" },
            { 14, "Marketing" },
            { 15, "Non-Profit" },
            { 16, "Comedy" },
            { 17, "Interviews" },
            { 18, "Improv" },
            { 19, "Stand-Up" },
            { 20, "Education" },
            { 21, "Courses" },
            { 22, "How-To" },
            { 23, "Language" },
            { 24, "Learning" },
            { 25, "Self-Improvement" },
            { 26, "Fiction" },
            { 27, "Drama" },
            { 28, "History" },
            { 29, "Health" },
            { 30, "Fitness" },
            { 31, "Alternative" },
            { 32, "Medicine" },
            { 33, "Mental" },
            { 34, "Nutrition" },
            { 35, "Sexuality" },
            { 36, "Kids" },
            { 37, "Family" },
            { 38, "Parenting" },
            { 39, "Pets" },
            { 40, "Animals" },
            { 41, "Stories" },
            { 42, "Leisure" },
            { 43, "Animation" },
            { 44, "Manga" },
            { 45, "Automotive" },
            { 46, "Aviation" },
            { 47, "Crafts" },
            { 48, "Games" },
            { 49, "Hobbies" },
            { 50, "Home" },
            { 51, "Garden" },
            { 52, "Video-Games" },
            { 53, "Music" },
            { 54, "Commentary" },
            { 55, "News" },
            { 56, "Daily" },
            { 57, "Entertainment" },
            { 58, "Government" },
            { 59, "Politics" },
            { 60, "Buddhism" },
            { 61, "Christianity" },
            { 62, "Hinduism" },
            { 63, "Islam" },
            { 64, "Judaism" },
            { 65, "Religion" },
            { 66, "Spirituality" },
            { 67, "Science" },
            { 68, "Astronomy" },
            { 69, "Chemistry" },
            { 70, "Earth" },
            { 71, "Life" },
            { 72, "Mathematics" },
            { 73, "Natural" },
            { 74, "Nature" },
            { 75, "Physics" },
            { 76, "Social" },
            { 77, "Society" },
            { 78, "Culture" },
            { 79, "Documentary" },
            { 80, "Personal" },
            { 81, "Journals" },
            { 82, "Philosophy" },
            { 83, "Places" },
            { 84, "Travel" },
            { 85, "Relationships" },
            { 86, "Sports" },
            { 87, "Baseball" },
            { 88, "Basketball" },
            { 89, "Cricket" },
            { 90, "Fantasy" },
            { 91, "Football" },
            { 92, "Golf" },
            { 93, "Hockey" },
            { 94, "Rugby" },
            { 95, "Running" },
            { 96, "Soccer" },
            { 97, "Swimming" },
            { 98, "Tennis" },
            { 99, "Volleyball" },
            { 100, "Wilderness" },
            { 101, "Wrestling" },
            { 102, "Technology" },
            { 103, "True Crime" },
            { 104, "TV" },
            { 105, "Film" },
            { 106, "After-Shows" },
            { 107, "Reviews" },
            { 108, "Climate" },
            { 109, "Weather" },
            { 110, "Tabletop" },
            { 111, "Role-Playing" },
            { 113, "Cryptocurrency" }
        };
}